<testsuites>
	<testsuite name="UndoRedoStack" tests="11">
		<testcase classname="UndoRedoStack" name="UndoRedoStackTest::DoIt"/>
		<testcase classname="UndoRedoStack" name="UndoRedoStackTest::DoItWithException"/>
		<testcase classname="UndoRedoStack" name="UndoRedoStackTest::DoItExceptionNeutral"/>
		<testcase classname="UndoRedoStack" name="UndoRedoStackTest::Undo"/>
		<testcase classname="UndoRedoStack" name="UndoRedoStackTest::UndoWithException"/>
		<testcase classname="UndoRedoStack" name="UndoRedoStackTest::UndoExceptionNeutral"/>
		<testcase classname="UndoRedoStack" name="UndoRedoStackTest::Redo">
			<failure message="..\src\UndoRedoStackTest.cpp:117 Redo: expected == result expected:	3	but was:	0	">
Redo: expected == result expected:	3	but was:	0	
			</failure>
		</testcase>
		<testcase classname="UndoRedoStack" name="UndoRedoStackTest::RedoWithException"/>
		<testcase classname="UndoRedoStack" name="UndoRedoStackTest::RedoExceptionNeutral"/>
		<testcase classname="UndoRedoStack" name="UndoRedoStackTest::IsRedoable"/>
		<testcase classname="UndoRedoStack" name="UndoRedoStackTest::IsUndoable"/>
	</testsuite>
	<testsuite name="UndoRedoManager" tests="9">
		<testcase classname="UndoRedoManager" name="UndoRedoManagerTest::IsModifiedSimple"/>
		<testcase classname="UndoRedoManager" name="UndoRedoManagerTest::IsModifiedAndIsRedoableWithNewCommand"/>
		<testcase classname="UndoRedoManager" name="UndoRedoManagerTest::ResetModified"/>
		<testcase classname="UndoRedoManager" name="UndoRedoManagerTest::IsModifiedwithExceptionDoIt"/>
		<testcase classname="UndoRedoManager" name="UndoRedoManagerTest::IsModifiedtwithExceptionUndo"/>
		<testcase classname="UndoRedoManager" name="UndoRedoManagerTest::IsModifiedtwithExceptionRedo"/>
		<testcase classname="UndoRedoManager" name="UndoRedoManagerTest::DoItExceptionNeutral"/>
		<testcase classname="UndoRedoManager" name="UndoRedoManagerTest::RedoExceptionNeutral"/>
		<testcase classname="UndoRedoManager" name="UndoRedoManagerTest::UndoExceptionNeutral"/>
	</testsuite>
	<testsuite name="CompositeCommand" tests="7">
		<testcase classname="CompositeCommand" name="CompositeCommandTest::DoItCommand"/>
		<testcase classname="CompositeCommand" name="CompositeCommandTest::DoItCommandWithException">
			<failure message="..\src\CompositeCommandTest.cpp:42 DoItCommandWithException: expected == result expected:	0	but was:	-2	">
DoItCommandWithException: expected == result expected:	0	but was:	-2	
			</failure>
		</testcase>
		<testcase classname="CompositeCommand" name="CompositeCommandTest::testUndoRedoDoIt"/>
		<testcase classname="CompositeCommand" name="CompositeCommandTest::UndoWithException">
			<failure message="..\src\CompositeCommandTest.cpp:92 UndoWithException: expected == result expected:	1	but was:	2	">
UndoWithException: expected == result expected:	1	but was:	2	
			</failure>
		</testcase>
		<testcase classname="CompositeCommand" name="CompositeCommandTest::DoItExceptionNeutral"/>
		<testcase classname="CompositeCommand" name="CompositeCommandTest::UndoExceptionNeutral"/>
		<testcase classname="CompositeCommand" name="CompositeCommandTest::RedoExceptionNeutral"/>
	</testsuite>
</testsuites>
